2. Getting Started with Processing (One Week)
2.0 Basic Materials
  2.0.1 Introduction
    {Page;Getting Started with Processing;getting-started-with-processing}
  2.0.2 Daily Sketches and Responses
    {Discussion;Sketches - Week Two;18006;2016-09-18}
2.1 Phase One (Due Wednesday)
  2.1.1 Try: Color in Processing
    {Discussion;Color in Processing;18007;2016-09-14;50}
  2.1.2 Try: Variables, Revisited
    {Discussion;Color in Processing;18008;2016-09-14;50}
  2.1.3 Make: Remix Processing Work
    {Discussion;Remix Processing Work;18009;2016-09-14;50}
2.2 Phase Two (Due Sunday)
  2.2.1 Make: Building
    {Discussion;Building;18010;2016-09-18;50}
  2.2.2 Make: Self Portrait
    {Discussion;Building;18011;2016-09-18;50}
2.3 Phase Three (Due Tuesday/Wednesday)
  2.3.1 Critique: Remixed Processing Work
    {Assignment;Critique Remixed Processing Work;22612;2016-09-20;20}
  2.3.2 Reflect and Synthesize: Remixed Work
    {Assignment;Remixed Processing Work;22613;2016-09-21;30}
