1. Getting Started (One Week)
1.0 Basic Materials
  1.0.1 Introduction
    {Page;Getting Started;getting-started}
  1.0.2 Daily Sketches and Responses
    {Discussion;Sketches - Week One;17999;2016-09-11}
1.1 Phase One (Due Wednesday)
  1.1.1 Watch, Reflect, Respond: About Processing
    {Discussion;About Processing;18000;2016-09-07}
  1.1.2 Read, Reflect, Respond: Radical Bricolage
    {Discussion;Radical Bricolage;18001;2016-09-07}
  1.1.3 Find, Comment, Respond: Digital Artwork
    {Discussion;Digital Artwork;18002;2016-09-07}
  1.1.4 Find, Comment, Respond: Initial Processing Examples
    {Discussion;Initial Processing Examples;18003;2016-09-07}
  1.1.5 Find and Analyze: Analog Algorithmic Work
    {Discussion;Analog Algorithmic Work;18004;2016-09-07}
1.2 Phase Two (Due Sunday)
  1.2.1 Try: An Abbreviated Introduction to Processing
    {Discussion;An Abbreviated Introduction to Processing;18005;2016-09-07;20}
  1.2.2 Make: Analog Work
    {Assignment;Algorithmic Analog Work;22604;2016-09-11;20}
1.3 Phase Three (Due Tuesday/Wednesday)
  1.3.1 Reflect
    {Assignment;Reflections on Algorithms;22605;2016-09-13;10}
