3. Making Choices (One Week)
3.0 Basic Materials
  3.0.1 Introduction
    {Page;Making Choices;making-choices}
  3.0.2 Daily Sketches and Responses
    {Discussion;Sketches - Week Three;18014;2016-09-25}
3.1 Phase One (Due Wednesday)
  3.1.1 Make: Citiscape
    {Discussion;Citiscape;18015;2016-09-21;20}
  3.1.2 Try: Randomness
    {Discussion;Randomness;18016;2016-09-21;20}
  3.1.3 Try: Conditionals
    {Discussion;Conditionals;18017;2016-09-21;20}
3.2 Phase Two (Due Sunday)
  3.2.1 Discuss: Ownership (Analog Works, Citiscapes)
    {Discussion;Ownership Week Three;18018;2016-09-25;50}
  3.2.2 Make: Interacting Shapes
    {Discussion;Interacting Shapes;18019;2016-09-25;50}
3.3 Phase Three (Due Tuesday/Wednesday)
  3.3.1 Critique: Interacting Shapes
    {Assignment;Critique: Interacting Shapes;22622;2016-09-27;20}
  3.3.2 Synthesize, Reflect, and REspond: Interacting Shapes
    {Assignment;Reflect: Interacting Shapes;22623;2016-09-28;30}
