#!/usr/bin/perl

# +------+-----------------------------------------------------------
# | Main |
# +------+

my ($dir) = @ARGV;
if (! -d $dir) { die "Could not find directory '$dir'"; }
if (! -X $dir) { die "Could not write director '$dir'"; }

copyDir("Assignments");
copyDir("Discussions");

# +---------+--------------------------------------------------------
# | Helpers |
# +---------+

sub copyDir($) 
{
  my ($source) = @_;
  opendir(my $dh, $source) || die "Could not open $source\n";
  chdir $dir;
  while (readdir $dh) {
    my $file = $_;
    if ($file =~ m/instructions.md$/) {
      if (-f $file) { unlink $file; }
      symlink "../$source/$file", $file;
      my $html = $file;
      $html =~ s/.md$/.html/;
      system "touch -t 200001010000 $html";
    } # if
  } # while
  close $dh;
  chdir "..";
} # copyDir

