#!/usr/bin/perl

# Copy the introductions to one of the staging directories.

# +------+-----------------------------------------------------------
# | Main |
# +------+

my ($dir) = @ARGV;
if (! -d $dir) { die "Could not find directory '$dir'"; }
if (! -X $dir) { die "Could not write director '$dir'"; }
copyDir("Introductions");

# +---------+--------------------------------------------------------
# | Helpers |
# +---------+

sub copyDir($) 
{
  my ($source) = @_;
  opendir(my $dh, $source) || die "Could not open $source\n";
  chdir $dir;
  while (readdir $dh) {
    my $file = $_;
    if (($file =~ m/.md$/) && ($file !~ m/^_/)) {
      if (-f $file) { unlink $file; }
      symlink "../$source/$file", $file;
      my $html = $file;
      $html =~ s/.md$/.html/;
      system "touch -t 200001010000 $html";
    } # if
  } # while
  close $dh;
  chdir "..";
} # copyDir

