#!/usr/bin/perl
# delete-assignment id 
#   Delete an assignment

# +-----------+------------------------------------------------------
# | Libraries |
# +-----------+

use HTTP::Request::Common (DELETE);
use Canvas::Setup;
use Canvas::General;

# +------+-----------------------------------------------------------
# | Main |
# +------+

# submitVerbose();
foreach my $id (@ARGV) {
  print STDERR "Deleting assignment '$id'\n";
  my $req = DELETE canvasURL("assignments/$id");
  submitRequest($req);
}

exit 0;
